# Generated by Django 4.0.3 on 2022-03-19 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0003_alter_futbolista_club_futbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surfista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=30)),
                ('pais', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tenista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=30)),
                ('club_tenis', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Cerrajero',
        ),
    ]
