# Generated by Django 4.0.3 on 2022-04-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0004_surfista_tenista_delete_cerrajero'),
    ]

    operations = [
        migrations.AddField(
            model_name='surfista',
            name='folleto',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
