# Generated by Django 4.0.3 on 2022-04-13 02:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0006_remove_surfista_folleto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surfista',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
