# Generated by Django 4.0.3 on 2022-04-23 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0007_surfista_fecha_creacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Futbolista',
        ),
        migrations.DeleteModel(
            name='Tenista',
        ),
        migrations.AddField(
            model_name='surfista',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='foto'),
        ),
    ]
